server:
    error:
        include-exception: false
        include-message: always
        include-stacktrace: on_param

spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/oauth2
        username: sa
        password:
        driver-class-name: org.h2.Driver
    
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            # show_sql: true
            format_sql: true
    
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: e8b57aa5ea243d475ced
                        clientSecret: 743c8ef1d46f1e1467ecc10585a3d1a48eebc5fc
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - user:email
                            - read:user
                    google:
                        clientId: 1059590504781-ip29uepiq6jpf91ais9r3nbrfhgagsv5.apps.googleusercontent.com
                        clientSecret: 4lOnw-_HiXx0-R_1-ntiFx-8
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile
                    facebook:
                        clientId: 461829631817428
                        clientSecret: c3f1d4193465404a7f4cb34f0b85267b
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Facebook은 이제 https 리디렉션 URI 사용을 요구하므로 앱이 프로덕션에서 https를 지원하는지 확인하세요.
                        scope:
                            - email
                            - public_profile
                provider:
                    facebook:
                        authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
                        tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
                        userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

app:
    auth:
        jwtSecret: templateSecretKey
        jwtExpirationMs: 86400000
    oauth2:
        authorizedRedirectUris:
            - http://localhost:8080/oauth2/redirect

